spring:
  application:
    name: content-service
  datasource:
    url: jdbc:mysql://localhost:3306/mye3?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mye3
    password: mye3
  redis:
    host: localhost
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
dubbo:
  registry:
    address: zookeeper://localhost:2181
    check: false
  protocol:
    port: 20882
  consumer:
    check: false
  scan:
    base-packages: com.summer.mye3.content.service.impl



