spring:
  application:
    name: sso-service
  datasource:
    url: jdbc:mysql://localhost:3306/mye3?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mye3
    password: mye3
  redis:
    host: localhost
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
dubbo:
  registry:
    address: zookeeper://localhost:2181
    check: false
  protocol:
    port: 20883
  consumer:
    check: false
  scan:
    base-packages: com.summer.mye3.sso.service.impl

#session\u7684\u8fc7\u671f\u65f6\u95f4
SESSION_EXPIRE: 1800