host: localhost
spring:
  application:
    name: sso-service
  datasource:
    url: jdbc:mysql://${host}:3306/mye3?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mye3
    password: mye3
  redis:
    host: ${host}
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
dubbo:
  registry:
    address: zookeeper://${host}:2181
    check: false
  protocol:
    port: 20883
  consumer:
    check: false
  scan:
    base-packages: com.summer.mye3.sso.service.impl

#session的过期时间
SESSION_EXPIRE: 1800