host: localhost
spring:
  application:
    name: item-web
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false
server:
  port: 8086

dubbo:
  registry:
    address: zookeeper://${host}:2181
  consumer:
    check: false
#静态页面输出目录
HTML_GEN_PATH: /temp/JavaEE32/freemarker/item/