spring:
  application:
    name: search-web
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  #关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false
server:
  port: 8085

dubbo:
  registry:
    address: zookeeper://localhost:2181
  consumer:
    check: false
#\u641c\u7d22\u7ed3\u679c\u6bcf\u9875\u663e\u793a\u7684\u8bb0\u5f55\u6570
SEARCH_RESULT_ROWS: 60