spring:
  application:
    name: search-web
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  #关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false
server:
  port: 8085

dubbo:
  registry:
    address: zookeeper://localhost:2181
  consumer:
    check: false
#搜索结果每页显示的记录数
SEARCH_RESULT_ROWS: 60