spring:
  application:
    name: manage-web
  mvc:
    view:
      suffix: /jsp/
      prefix: '.jsp'

server:
  port: 8081
  servlet:
    context-path: /manage-web

dubbo:
  registry:
    address: zookeeper://localhost:2181
  consumer:
    check: false
