spring:
  application:
    name: manage-web
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
#关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false
server:
  port: 8082
  servlet:
    context-path: /portal-web

dubbo:
  registry:
    address: zookeeper://localhost:2181
  consumer:
    check: false
#轮播图内容的分类
CONTENT_LUNBO_ID: 89
#sso系统的url地址
SSO_URL: http://localhost:8083