spring:
  application:
    name: manage-web
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
#关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false
server:
  port: 8082
  servlet:
    context-path: /portal-web

dubbo:
  registry:
    address: zookeeper://localhost:2181
  consumer:
    check: false
#\u8F6E\u64AD\u56FE\u5185\u5BB9\u7684\u5206\u7C7B
CONTENT_LUNBO_ID: 89
  #sso\u7CFB\u7EDF\u7684url\u5730\u5740
SSO_URL: http://localhost:8083